### ISSUE TITLE
 Cmake  error in CMakeList

### ISSUE THREAD

**Issue by yuan158588** [amiller27/uav_target_planner#1]
![image](https://user-images.githubusercontent.com/38127864/49139729-811c6600-f32d-11e8-9278-77f0cfda8416.png)

As a beginner, i can't solve this problem.

**Comment by amiller27** [comment]
This is a ROS package, so to get it to build you'll need to set up a ROS workspace and use `catkin_make` to build the project.  I'm assuming from the path in your post that you're on Windows; it might be possible to get it to work there with WSL, but ROS is really designed to be used on Linux.

**Comment by yuan158588** [comment]
> This is a ROS package, so to get it to build you'll need to set up a ROS workspace and use `catkin_make` to build the project. I'm assuming from the path in your post that you're on Windows; it might be possible to get it to work there with WSL, but ROS is really designed to be used on Linux.

Thank you for your reply! I will try to run it first.
